# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

So for instance if you wanted to add two arrays together on elements by elements basis you would just say array plus array.

In this case I'm just adding in array to itself,so essentially every number's been doubled.

In [3]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
# Subtraction

arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# Multiplication

arr * arr 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Notes: 

Single number basically broadcasts that number to every element in the array so, the operation occurs also on an element by element basis meaning if I want to.

Add a hundred to every element in the array. 

I could say plus and then the scalar itself.

And that would add 100 every element in the array.

In [7]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
# That work for any sort of operation

arr * 10

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

So for instance if I try to say 1 divided by zero in Python I will get in that's an actual error has zero division error which makes sense because you can't divide a number by zero.



In [9]:
1/0

ZeroDivisionError: division by zero

### Notes: 

However numpy won't give you the same error. So if I try to say a rate divided by Array.

Notice the very first element is zero.

I will try to say zero divided by zero which doesn't really make sense.

However none numpy will issue a warning.

It will say invalid value encountered in truth like here and it'll just give you a null.

If you try to divide zero by zero everything else is OK for it says 1 divided by 1 is 1 2 divided by 2 is 1 as well.



In [10]:
arr / arr

/Users/Giuliano/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

### Notes: 

However on the very first ones are divided by zero executed and gave you a name or no object back.

It didn't actually provide an error for you meaning you still get an output that's important to note the distinction there.

That means if you have some sort of operation in your code you actually won't get an error.

### Notes: 

So for instance 1 divided by 0 instead of 0  you'll also get a warning.

But in this case shows infinity instead of a null.

So again you get a divide by zero and countered and true the vide warning here.

However it still executes the code and you get enough to signify infinity for the one divided by zero.

In [16]:
1 / arr 

/Users/Giuliano/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
#  So everything has been squared in the array 

arr ** 2 

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [17]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
np.max(arr) #same as arr.max()

9

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

You can say that log and if something doesn't work for instance the log of zero is technically negative infinity you'll actually receive a runtime warning.

Divided by zero.

But it will give you negative infinity is the answer.

In [21]:
np.log(arr)

/Users/Giuliano/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])