# Numpy Array Indexing

In [4]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Notes: 

Simplest way to pick out one or some of the elements of an array looks a lot like indexing from a python list.

Basically you're going to use brackets and slice notation in order to do this.

Passen square brackets and then to get a single value at an index which you can do just passing a number.

In [5]:
arr[1]

1

If I want to get the values in a range just like a python list.

I can use slice notation meaning I can say the starting index and the stop index.

In [7]:
# Starting from the 2nd position but no include the 5th
# It means that start at index 1 in this case is 0
# index 2 in this case is 1
# index 5 in this case is actually 5

arr[1:5]

array([1, 2, 3, 4])

In [8]:
# So for instance if I want everything up to index 6 instead of specifying the starting parameter as 0
# I can just put a colon and then put 6 then turn everything up to the start of the array to index 6.

arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Notes: 

Something to note when you're using this notation of a number and then a colon is that you're not actually grabbing at index 5 and beyond.

You're grabbing everything be on index 5 because remember indexing as far as notation in **Python** **starts at zero**.

But essentially this works exactly the same as it does for a normal Python list.

Arrays differ from a normal Python list because of their ability to broadcast.

In [11]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Example of broacast in Python Arrays

So it's going to be zero one two three four and then I consider it equal to the number 100.

And what that it's going to do.

It's going to broadcast that value to those first five digits to all be 100.

In [12]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!



In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

Here's where you have to pay careful attention.

If I called back the array it's actually changed 99 not just on the slice but on the original array.

I had called two.

So you should know how that change also occurs in the original array meaning the data is not copied.

In [16]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

And if I take a look at my array copy it's also the same thing.

But if I do a change to my array copy maybe by broadcasting every value to be 100.

And I check out array copy every value is 100.

But that original array is still unaffected by that broadcast in the command to 100.

In [19]:
arr_copy[0:5]=5
arr_copy

array([ 5,  5,  5,  5,  5, 99,  6,  7,  8,  9, 10])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Notes:

Basic premise here is that if you actually grab a slice of the array and set it as a variable without explicitly saying that you want a copy of the array you should keep in mind that you're just viewing a link to the original array and that changes you do will actually affect that original array.

Meaning that once the array is specified that it is a copy any changes made in it wouldn't affect the original array

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Notes: 

There's two general formats for grabbing elements from a to the array or Matrix.

There's the double bracket for it.

And then there's the single bracket formit with the comma.

Well let's say I wanted to grab the digit 5 so that's in the very first or index 0 row and in the very first column index 0 for double bracket notation I can pasan first the row I want and then the column I want.

So passing in 00 here will return the digit 5.

Since that's the elements in the first row in the first column.

In [23]:
# 1st Bracket row
# 2nd Bracket column

arr_2d[0][0]

5

In [29]:
# Entire row
arr_2d[1]

array([20, 25, 30])

In [30]:
arr_2d[2][1]

40

In [34]:
# Another way to do it using just only one square bracket and comma

arr_2d[1,2]

30

Let's say we wanted to grab from the top right corner.

Meaning I want to say 10 15 and 25 30 so this top right corner here's what I want to grab when I can go ahead and do is use slice notation in order to do this.

So I can say grab everything up to call a row to and then grab from column 1 onwards and that returns 10 15 25 30.

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

What we're saying is grab everything but not including rows 0 and 1 as the colon.

But then don't include two.

I'm saying slice it too and I'll go ahead and show that it's just a single command so I say Colon's to that returns  Go grab everything from Column 1 all the way to the end which basically means just drop all over this column 0 and that returns these two little subsections 10 15 and then 25 30.

In [36]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [37]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
# Grabbing 20,25,30

arr_2d[1]

array([20, 25, 30])

In [42]:
# Grabbing 35,40,45

#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [57]:
# Grabbing entire column

In [63]:
arr_2d[:,1]

array([10, 25, 40])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [43]:
#Set up matrix
arr2d = np.zeros((10,10))

In [44]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
#Length of array
arr_length = arr2d.shape[1]

In [47]:
arr_length

10

In [53]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [54]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [55]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [70]:
arr =  np.arange(10)

In [71]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# It returns boolens values containg True or FALSE

arr > 1

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [74]:
bool_arr = arr > 1

In [75]:
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

Now you can use that to actually do conditional selection.

Meaning I can pass that in two brackets and I will only get the results where this boolean array happened to be true.

In [77]:
# Just return where the boolen values happened to be true

arr[bool_arr]

array([2, 3, 4, 5, 6, 7, 8, 9])

Using a comparison operator on it will actually return a boolean array meaning an array of all boolean values.

Then I can use that boolean array to actually index or conditionally select elements from that original array where this happened to be true.

In [78]:
# Or simply we can do like that

arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# Conditional Selection

arr[arr>5]

array([6, 7, 8, 9])

In [81]:
arr[arr<4]

array([0, 1, 2, 3])

In [5]:
# Exercise

x = np.arange(50).reshape(5,10)

In [6]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [8]:
x[2:4,2:4]

array([[22, 23],
       [32, 33]])