# Numpy Arrays
 
- Numpy is a linear library for Python 

- And the reason it's so important for data science with Python is that almost all of the other libraries in the PI data ecosystem rely on PI as one of their main building blocks.


### Instalation

- Exclamation mark means run it as a shell command rather than a notebook command


!conda install numpy

!pip install numpy

### Difference between pip and conda

- pip is a package manager that facilitates installation, upgrade, and uninstallation of python packages. It also works with virtual python environments. conda is a package manager for any software (installation, upgrade and uninstallation). It also works with virtual system environments

### Vector and Matrices

- The empire is essentially come in two flavors either vectors or matrices.

- Vectors are strictly one d arrays and matrices are two the two that missional.

- We should also note that a matrix can still only have one row or one column.

- Vectors or two dimensional matrices but they can both be called arrays.


In [9]:
# Creating an object to my list

my_list = [1,2,3]

In [7]:
# Importing numpy library 

import numpy as np

In [6]:
# NowI can cast a normal Python list into an array.

np.array(my_list)

array([1, 2, 3])

In [11]:
# Assigning it and then just calling array off of that. 

arr = np.array(my_list)

In [13]:
# Now it will return back a one dimensional array

arr

array([1, 2, 3])

In [15]:
# If I want to get a two dimensional array or a matrix.
# I can cast a list of lists.

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
# So notice I get back a list of lists and then if I cast that to an array I will get back a two dimensional
# array and that's noted both by the way it's presented as output but also more importantly as the number 
# of brackets shown on the closing and opening ends of this array.

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Notes:

I have two sets of brackets which will indicate that Z to that mentionable array has three rows and three columns and that's how you can cast normal Python lists or list of lists to umpire range.

## np.arange()

numpy.arange([start, ]stop, [step, ]dtype=None)

So notice you have a start a stop and then a step size is a third argument and the return evenly spaced values within this given interval.



In [21]:
# So if I just say from 0 to 10 remember just like in Python's range indexing starts at zero.
# It will go up to but not including to 10.
# I'll get an array back from 0 all the way to 9.

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Notes:

Note the brackets and parentheses in this case just one square brackets because it's not a list

In [24]:
# So I want to go from zero all the way to 10 after Z. I have to say zero comma 11 and that's what I get back out.

np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# And then at a step size of two so that I'd jump in steps of 2 0 2 4 6 8 10.

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [28]:
# For instance if you want to generate arrays of all zeros you can pass in a single digit.

np.zeros(3)

array([0., 0., 0.])

In [31]:
# Using tupples of dimensions 
# you want the first number is going to represent the number of rows and the second number 
# in that tuple is going to represent the number of columns.

np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# Another example with array of ones

np.ones(4)

array([1., 1., 1., 1.])

In [33]:
# Another examples with array of one using tupples

np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.linspace

What Lin space is going to do is it's actually going to take in a third argument of the number of points you wants me going to show you what I mean by that I can say P Gotland space and I get a pass and a start a stop and there's a third argument I'm going to pass in a number.
So let's say I have a start of zero and a stop of five and I want to get 10 evenly spaced points between zero to five.

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [37]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Notes:

I can pass in a third argument 10 and this returns back a one dimensional vector noted by the once set of brackets here of ten evenly spaced points from zero to five and I can change this third argument to whatever number I want.

So if I want 100 evenly spaced points from zero to five I can just pass that in and that returns a much larger one dimensional array and keep in mind even though it looks like this is to them as far as the way it's being printed out
you can tell it's one dimensional by the fact that there's only one bracket here in front of the array when you're dealing with two dimensions you'll see that you have two sets of brackets on opening or closing at the ends.

3d Matrix will have three brackets etc..

In [39]:
# Example 

np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Notes:

Again don't confuse space with arrange lint space will take in the third argument as the number of points you want arrange will take in that argument as the step size you want.

## np.eye

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

If you're not familiar is a useful matrix when you're dealing with linear algebra problems and it's basically just a two dimensional square matrix meaning the number of rows is the same as a number of columns and you have a diagonal of ones that everything else is zeros and that's the reason it only takes a single digit as an argument because it said that the matrix must be square as the output.

In mathematics, 

- Square matrix is a matrix with the same number of rows and columns.

- Any two square matrices of the same order can be added and multiplied.

- Square matrices are often used to represent simple linear transformations, such as shearing or rotation. 

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random sampling (np.random)
- .rand
- .randn
- .randint
- .reshape
- .max of an array
- .min of an array

### Notes:

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

In [45]:
# And that means if I want just eight one dimensional array of random numbers uniformly distributed 
# from 0 to 1 I can pass in a single digit and I'll get back that one dimensional array.

np.random.rand(8)

array([0.18496393, 0.30532364, 0.49541998, 0.19191097, 0.41835672,
       0.77830701, 0.21769435, 0.70107514])

### Notes:

Unlike the previous functions you worked with instead of passing in a tuple. I'll actually just pass in the dimensions as separate arguments.**

**So that means if I want a five by five matrix of random numbers I just pass and 5 come a 5 instead of the tuple and working with these random libraries.

In [49]:
np.random.rand(5,5)

array([[0.14942086, 0.40950981, 0.89472106, 0.68434331, 0.69904411],
       [0.90750597, 0.94288651, 0.75994059, 0.92964702, 0.90078253],
       [0.70594611, 0.38796038, 0.44809204, 0.29931574, 0.74733258],
       [0.37437174, 0.7818454 , 0.99276965, 0.86303105, 0.62782869],
       [0.67947907, 0.53763181, 0.85543114, 0.49736094, 0.86370028]])

### Notes:

If we want to return a sample or many samples from the standard normal distribution or a Gaussian distribution instead of using .rand we can use .randn and that means will return numbers not from a uniform distribution from 0 to 1 but instead from a standard normal distribution center around zero and that means I can go ahead and pass in two and I get two random numbers from a standard normal distribution.

In [50]:
np.random.randn(2)

array([ 0.45472567, -1.26716764])

In [51]:
# If I want it in 2d Array

np.random.randn(4,4)

array([[-1.3552443 , -0.36273045, -0.28263335,  0.64331931],
       [ 0.17109501,  0.49821291,  0.09633377,  0.22065847],
       [-1.41692353, -0.10485766,  0.48088293,  0.93804175],
       [ 1.11899423, -0.13693252, -1.11581285,  1.36654804]])

### Notes:

And no I don't pass a tuple here I just pass in each time mention as a separate argument and I can see by the set of two brackets is a two dimensional matrix as an output and the final random method of creating an array.

In [57]:
# numpy.random.randint(low, high=None, size=None, dtype=int)

np.random.randint(0,10)

8

In [59]:
np.random.randint(0,100)

58

In [66]:
# with 500 random numbers 

np.random.randint(0,100,500)

array([79, 81,  5, 75, 97,  9, 78, 88, 20, 41, 36, 55, 27, 42, 79,  6,  1,
       29, 13, 14, 58, 89,  7, 60, 27,  7, 95, 69, 26,  8, 25, 43, 49, 24,
       34, 69, 40, 53,  9, 26, 85,  0, 15, 73, 70,  9, 79, 96, 35, 96, 85,
       31, 71,  7, 12, 34, 25, 92, 90, 29, 83, 16, 34, 47, 59, 76, 87, 79,
       78, 56, 22, 35, 52, 90, 34, 79, 21, 54, 45,  9,  0, 77, 75, 52, 30,
       78, 72, 10,  1,  1, 58,  4, 77, 12, 26, 93, 88,  0, 51, 34, 14, 72,
       61, 74, 16, 19, 81, 12,  4, 33, 82, 11, 78, 83, 82, 65, 86, 52, 86,
       37, 77,  3, 73, 16, 59, 30, 55, 54, 77, 53, 66, 10, 30, 95, 95,  3,
       16, 89, 38, 37, 87, 63, 66, 99, 16, 86, 22, 64, 49,  3, 15, 34, 34,
       67, 59, 44, 49, 93, 17, 89, 83, 43, 80, 50, 60, 22,  6, 78, 25,  7,
       46,  8, 90, 33, 42, 17, 91,  2, 12,  1, 55, 94, 17, 28, 44, 53, 83,
       72, 85, 68, 55, 46,  4, 62, 32, 41, 63,  8, 11, 93, 62, 94,  5, 18,
        7, 57, 16, 10, 87, 40, 84, 16,  5, 43, 26, 94, 24, 76, 38, 11,  3,
       96, 54, 29, 63, 98

### Notes:

The high x exclusive meaning one has the chance of being selected but 100 is not and if you want a particular number of random integers you can pass them in as a third argument.

So from to random integers from 1 to 100 but not including 100 and I can just pass and 10 there and there are 10 random integers inclusive on the low in an exclusive on the high end.

arr = np.array(25)

In [67]:
arr = np.arange(25)

In [68]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
ranarr = np.random.randint(0,50,10)

In [72]:
ranarr

array([35,  9, 13, 26, 33, 16, 41, 14, 42, 34])

In [73]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
ranarr.reshape(2,5)

array([[35,  9, 13, 26, 33],
       [16, 41, 14, 42, 34]])

### Notes:

So for example if I want to reshape that arrayis twenty five digits zero to 24. I can reshape it as a 5 by 5 array using reshape and then passen the number of rows you want and the number of columns.

Keep in mind you'll get an error if you can't fill up that matrix completely. So for example if I wanted 5 by 10 I would need 50 elements to do that and I'm going to get an error here because the total size of the new array must be unchanged, meaning you need to fill up using only the digits you have or the elements you have a nice simple way to check this is that the number of rows times the number of columns is equal to the actual number of elements so five times five is equal to 25 and I know I have 25 elements in this array.

In [103]:
# max and min for arr

arr.max()
arr.min()

print("Max value for arr: {}".format(arr.max()))
print("Min value for arr: {}".format(arr.min()))

Max value for arr: 24
Min value for arr: 0


In [102]:
# max and min for ranarr
ranarr.max()
ranarr.min()

print("Max value for ranarr: {}".format(ranarr.max()))
print("Min value for ranarr: {}".format(ranarr.min()))

Max value for ranarr: 42
Min value for ranarr: 9


### Notes: 

We can actually figure out the location of the max or min values by specifying our max or min.

Meaning if I want to actually know what index value is this Max located at 49 I can say .argmax and that will return the index location of the max value.

In [104]:
ranarr

array([35,  9, 13, 26, 33, 16, 41, 14, 42, 34])

In [106]:
# Return the positions of the max number

ranarr.argmax()

8

In [107]:
ranarr.max()

42

Python starts counting from zero so it's at eight position

In [109]:
# Return the positions of the min number

ranarr.argmin()

1

In [112]:
# Shows what type of vector it's 
# 1d
# 2d
# 3d

arr.shape

(25,)

If you ever want to figure out the shape of the vector you can say are shaped in a low return back the shape. Notice here I get 25 comma and that's indicating that arr array was just a one dimensional vector

In [113]:
# If you ever want to reshape to a new dimensional

arr = arr.reshape(5,5)

In [114]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [115]:
# If you're ever curious of what data type you have an array you can just say arr and type as an attribute 
#  dtype in it will return the actual data type that's in your way.

arr.dtype

dtype('int64')

**If you ever want to stopping type in np.random you can import np.random from numpy.random**


In [128]:
from numpy.random import randint
from numpy.random import randn


In [129]:
randint(0,100,5)

array([55, 44, 23, 34, 55])

In [130]:
randn(10)

array([-0.07875488, -0.17044566, -0.05047618, -0.71093055, -0.18384711,
       -0.45826934,  0.99022179, -0.44622269, -1.83841807, -1.3080084 ])